from __future__ import annotations

import argparse
import base64
import csv
import hashlib
import io
import json
import os
import tempfile
import zipfile
from pathlib import Path
from typing import Mapping


DEFAULT_VERSION = "0.8.4+infoskill1"
HYBRID_MARKER = b"INFOSKILL_HYBRID_PREFIX_API = 1"


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _dist_info_dir(entries: Mapping[str, bytes]) -> str:
    candidates = {
        name.split("/", 1)[0]
        for name in entries
        if ".dist-info/" in name
    }
    if len(candidates) != 1:
        raise RuntimeError(
            f"expected exactly one .dist-info directory, found {sorted(candidates)}"
        )
    return candidates.pop()


def _native_extensions(entries: Mapping[str, bytes]) -> list[str]:
    return sorted(
        name
        for name in entries
        if name.startswith("vllm/_C.") and name.endswith(".so")
    )


def _metadata_version(metadata: bytes) -> str:
    versions = [
        line.removeprefix(b"Version: ").decode("utf-8")
        for line in metadata.splitlines()
        if line.startswith(b"Version: ")
    ]
    if len(versions) != 1:
        raise RuntimeError("wheel METADATA must contain exactly one Version field")
    return versions[0]


def inspect_wheel_entries(entries: Mapping[str, bytes]) -> dict[str, object]:
    native_extensions = _native_extensions(entries)
    if not native_extensions:
        raise RuntimeError("vLLM wheel is missing the native extension vllm/_C*.so")

    data_module = entries.get("vllm/inputs/data.py")
    if data_module is None or HYBRID_MARKER not in data_module:
        raise RuntimeError("vLLM wheel is missing the INFO-SKILL hybrid-prefix marker")

    dist_info = _dist_info_dir(entries)
    metadata_path = f"{dist_info}/METADATA"
    if metadata_path not in entries:
        raise RuntimeError("vLLM wheel is missing dist-info/METADATA")

    return {
        "dist_info": dist_info,
        "hybrid_prefix_api": 1,
        "native_extensions": native_extensions,
        "version": _metadata_version(entries[metadata_path]),
    }


def _replace_metadata_version(metadata: bytes, version: str) -> bytes:
    lines = metadata.splitlines(keepends=True)
    matches = [index for index, line in enumerate(lines) if line.startswith(b"Version: ")]
    if len(matches) != 1:
        raise RuntimeError("wheel METADATA must contain exactly one Version field")
    newline = b"\r\n" if lines[matches[0]].endswith(b"\r\n") else b"\n"
    lines[matches[0]] = f"Version: {version}".encode("utf-8") + newline
    return b"".join(lines)


def _version_module(version: str) -> bytes:
    public = version.split("+", 1)[0]
    numeric = tuple(int(part) for part in public.split("."))
    local = version.split("+", 1)[1] if "+" in version else None
    version_tuple = (*numeric, local) if local is not None else numeric
    return (
        "# Generated by INFO-SKILL wheel repackaging.\n"
        f"__version__ = version = {version!r}\n"
        f"__version_tuple__ = version_tuple = {version_tuple!r}\n"
        "__commit_id__ = commit_id = None\n"
    ).encode("utf-8")


def repackage_entries(
    base: Mapping[str, bytes],
    patched: Mapping[str, bytes],
    version: str,
) -> dict[str, bytes]:
    if not _native_extensions(base):
        raise RuntimeError("base vLLM wheel is missing the native extension vllm/_C*.so")

    missing = sorted(set(patched) - set(base))
    if missing:
        raise RuntimeError(f"patched files are absent from the base wheel: {missing}")

    old_dist_info = _dist_info_dir(base)
    distribution = old_dist_info.split("-", 1)[0]
    safe_version = version.replace("-", "_")
    new_dist_info = f"{distribution}-{safe_version}.dist-info"
    old_record = f"{old_dist_info}/RECORD"

    result: dict[str, bytes] = {}
    for old_name, original in base.items():
        if old_name == old_record:
            continue
        new_name = old_name
        if old_name.startswith(f"{old_dist_info}/"):
            new_name = f"{new_dist_info}/{old_name[len(old_dist_info) + 1:]}"

        content = patched.get(old_name, original)
        if old_name == f"{old_dist_info}/METADATA":
            content = _replace_metadata_version(content, version)
        elif old_name == "vllm/_version.py":
            content = _version_module(version)
        result[new_name] = content

    return result


def _record(entries: Mapping[str, bytes], record_path: str) -> bytes:
    output = io.StringIO(newline="")
    writer = csv.writer(output, lineterminator="\n")
    for name in sorted(entries):
        content = entries[name]
        digest = base64.urlsafe_b64encode(hashlib.sha256(content).digest()).rstrip(b"=")
        writer.writerow([name, f"sha256={digest.decode('ascii')}", len(content)])
    writer.writerow([record_path, "", ""])
    return output.getvalue().encode("utf-8")


def _read_wheel(path: Path) -> dict[str, bytes]:
    with zipfile.ZipFile(path) as wheel:
        names = [name for name in wheel.namelist() if not name.endswith("/")]
        if len(names) != len(set(names)):
            raise RuntimeError(f"wheel contains duplicate members: {path}")
        return {name: wheel.read(name) for name in names}


def _output_name(base_wheel: Path, version: str) -> str:
    stem = base_wheel.name.removesuffix(".whl")
    parts = stem.rsplit("-", 3)
    if len(parts) != 4:
        raise RuntimeError(f"cannot parse wheel filename: {base_wheel.name}")
    distribution_and_version, python_tag, abi_tag, platform_tag = parts
    distribution = distribution_and_version.split("-", 1)[0]
    return f"{distribution}-{version}-{python_tag}-{abi_tag}-{platform_tag}.whl"


def _write_wheel(path: Path, entries: Mapping[str, bytes]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    handle, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.", suffix=".tmp", dir=path.parent
    )
    os.close(handle)
    temporary = Path(temporary_name)
    try:
        with zipfile.ZipFile(
            temporary,
            mode="w",
            compression=zipfile.ZIP_DEFLATED,
            compresslevel=6,
        ) as wheel:
            for name in sorted(entries):
                info = zipfile.ZipInfo(name, date_time=(1980, 1, 1, 0, 0, 0))
                info.compress_type = zipfile.ZIP_DEFLATED
                info.external_attr = 0o644 << 16
                wheel.writestr(info, entries[name])
        os.replace(temporary, path)
    finally:
        temporary.unlink(missing_ok=True)


def repackage_wheel(
    base_wheel: Path,
    patched_source: Path,
    manifest_path: Path,
    output_dir: Path,
    version: str,
) -> tuple[Path, dict[str, object]]:
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    patched_paths = list(manifest["upstream_file_sha256"])
    patched = {
        relative: (patched_source / relative).read_bytes()
        for relative in patched_paths
    }
    entries = repackage_entries(_read_wheel(base_wheel), patched, version)
    dist_info = _dist_info_dir(entries)
    record_path = f"{dist_info}/RECORD"
    entries[record_path] = _record(entries, record_path)
    report = inspect_wheel_entries(entries)

    output = output_dir / _output_name(base_wheel, version)
    _write_wheel(output, entries)
    report.update(
        {
            "base_wheel": str(base_wheel),
            "base_wheel_sha256": _sha256(base_wheel),
            "output_wheel": str(output),
            "output_wheel_sha256": _sha256(output),
        }
    )
    return output, report


def inspect_wheel(path: Path) -> dict[str, object]:
    report = inspect_wheel_entries(_read_wheel(path))
    report.update({"wheel": str(path), "wheel_sha256": _sha256(path)})
    return report


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Repackage or verify an INFO-SKILL patched vLLM wheel"
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    repackage = subparsers.add_parser("repackage")
    repackage.add_argument("base_wheel", type=Path)
    repackage.add_argument("patched_source", type=Path)
    repackage.add_argument("manifest", type=Path)
    repackage.add_argument("output_dir", type=Path)
    repackage.add_argument("--version", default=DEFAULT_VERSION)

    verify = subparsers.add_parser("verify")
    verify.add_argument("wheel", type=Path)

    args = parser.parse_args()
    if args.command == "repackage":
        _, report = repackage_wheel(
            args.base_wheel.resolve(),
            args.patched_source.resolve(),
            args.manifest.resolve(),
            args.output_dir.resolve(),
            args.version,
        )
    else:
        report = inspect_wheel(args.wheel.resolve())
    print(json.dumps(report, ensure_ascii=False, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
