#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${PROJECT_ROOT}"
HANDOFF="${HANDOFF:?HANDOFF is required}"
GROUNDING_DATA="${GROUNDING_DATA:?GROUNDING_DATA is required}"
CONFIG="${CONFIG:-configs/alfworld_qwen25_7b.yaml}"
SKILL_BANK="${SKILL_BANK:-${HANDOFF}/skill-bank.json}"
SKILL_BANK_MANIFEST="${SKILL_BANK_MANIFEST:-${HANDOFF}/skill-bank-manifest.json}"
TARGET_UPDATES="${TARGET_UPDATES:-200}"

[[ -f "${HANDOFF}/checkpoint.complete.json" ]] || {
  echo "incomplete m1-handoff: ${HANDOFF}" >&2
  exit 2
}

GPUS="${GPUS:-0,1,2}" \
PROFILE=formal \
MAX_UPDATES=445 \
SEGMENT_END_UPDATE="${TARGET_UPDATES}" \
GROUNDING_DATA="${GROUNDING_DATA}" \
WARMSTART_HANDOFF="${HANDOFF}" \
SKILL_BANK="${SKILL_BANK}" \
SKILL_BANK_MANIFEST="${SKILL_BANK_MANIFEST}" \
EVAL_BATCH_SIZE="${EVAL_BATCH_SIZE:-64}" \
PERSISTENT_ROLLOUT_SESSION=1 \
ENVIRONMENT_BACKEND=native_batch \
POLICY_MAX_TOKENS_PER_GPU="${POLICY_MAX_TOKENS_PER_GPU:-12288}" \
ROLLOUT_MAX_BATCHED_TOKENS="${ROLLOUT_MAX_BATCHED_TOKENS:-16384}" \
HYBRID_PREFIX_CUDA_GRAPH=1 \
LORA_SHRINK_SPLIT_K_ONE=1 \
POLICY_GRADIENT_CLIP_MODE=joint \
CHECKPOINT_KEEP_RECENT=5 \
CHECKPOINT_KEEP_BEST_VALID=1 \
RUN_NAME="${RUN_NAME:-m1-handoff-formal-u${TARGET_UPDATES}}" \
bash scripts/run_alfworld.sh train infoskill "${CONFIG}"
